### ISSUE TITLE
Using pmwrite with a 32 bit number

### ISSUE THREAD

**Issue by ksmith0** [ksmith0/PixieSuite#2]
When setting a number with the 31st bit set the readback gives a smaller value. This is most likely due to a sign bit issue.

Can be replicate by:
pmwrite 2 TrigConfig3 3221487616

**Comment by cthornsb** [comment]
Fixed in commit 665684e4fc on April 22nd, 2015.  PixieInterface::WriteSglChanPar took a float as an argument and PixieInterface::WriteSglModPar took an int as an argument.  They were updated to take a double and an unsigned int respectively.  This brings them in line with the functions defined in the firmware (pixie16app.c).  This may be a feature of the newer firmware to allow pwrite/pmwrite to accept larger values.

**Comment by ksmith0** [comment]
This issue was moved to pixie16/PixieSuite2#24
